In [167]:
import numpy as np
import copy
import pandas as pd

In [168]:
# 일반 인덱싱한 데이터는 파이썬의 기본 데이터와 동일하게 동작
# scalar data - immutable
a = 10
b = a
b = 20
print(a)  # 10

#
ax = [1, 2, 3]
bx = ax
bx[0] = 100
print(ax)  # [100, 2, 3]

10
[100, 2, 3]


In [169]:
# copy 모듈의 copy(shallow copy - 얕은 복사)와 deepcopy(깊은 복사)
# 얕은 복사는 한 번 복제, 재귀적으로 수행하지 않음
# 깊은 복사는 재귀적으로 복제 수행

li = [1,2,3]
c = li.copy()  # 얕은 복사
c[0] = 100
print(li)

m = [[1,2,3],[4,5,6]]
c = m.copy()  # 얕은 복사
c[0][0] = 100
print(m)

d = copy.deepcopy(m)  # 깊은 복사
d[0][0] = 20
print(m)  # deepcopy는 복사본 - 수정해도 원본에 영향 주지 않음

[1, 2, 3]
[[100, 2, 3], [4, 5, 6]]
[[100, 2, 3], [4, 5, 6]]


In [170]:
# 일차원 배열과 이차원 배열 생성
li = list(range(1, 10)) # 일차원 list 생성
print(li, len(li), type(li))

# list 이용해서 ndarray 생성
ar = np.array(li)
matrix = ar.reshape(3,3)
print(ar, ar.shape, type(ar))
print(matrix, matrix.shape, type(matrix))

[1, 2, 3, 4, 5, 6, 7, 8, 9] 9 <class 'list'>
[1 2 3 4 5 6 7 8 9] (9,) <class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3) <class 'numpy.ndarray'>


In [171]:
# 인덱싱 - 데이터 1개 가져오기
data1 = ar[0]
print(data1)

data2 = matrix[0,0]
data3 = matrix[0][0]
print(data2)
print(data3)

# slicing
# 이차원 배열에서 행 하나 찾아오기
row = matrix[0]
print(row)

# 이차원 배열에서 열 하나 찾아오기
column = matrix[:, 0]
print(column)

1
1
1
[1 2 3]
[1 4 7]


In [172]:
# scalar - 원본 바뀌지 않음
data1 = 100
print(ar)

data2 = 100
print(matrix)

data3 = 100
print(matrix)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [173]:
# vector - 원본 바뀜
row[0] = 100
print(matrix)

column[0] = 20
print(matrix)

# 데이터 복제는 copy()
clone = matrix.copy()
clone[0][0] = 40
print(matrix)  # clone 수정해도 matrix 안 바뀜

[[100   2   3]
 [  4   5   6]
 [  7   8   9]]
[[20  2  3]
 [ 4  5  6]
 [ 7  8  9]]
[[20  2  3]
 [ 4  5  6]
 [ 7  8  9]]


## slicing

In [36]:
li = [1,2,3,4,5]
c = li[0:3]  # list slicing
s = li[0:3]
print(c)

ar = np.array(li)
d = ar[0:3]
e = ar[0:3]
print(d)

c[0] = 100
print(li)

d[0] = 100
print(ar)

[1, 2, 3]
[1 2 3]
[1, 2, 3, 4, 5]
[100   2   3   4   5]


## Fancy Indexing

In [38]:
# 인덱싱 할 때 list 이용하는 것
ar = np.array([1,2,3,4,5])
f = ar[[0,2]]
print(f)

f[0] = 100
print(ar)

[1 3]
[1 2 3 4 5]


In [41]:
# print([1,2,3] > 3)  # 에러
print(np.array([1,2,3]) > 3)


[False False False]


In [46]:
# boolean indexing : array 인덱스에 bool 배열 대입해서 True 데이터 추출
# 조건에 맞는 데이터만 추출할 때 사용
ar = np.array([1,2,3,4,5,6,7])
br = np.array([20,40,2,56,234,3010,23])
result = ar[(br >= 10) & (br <= 90)]
result1 = ar[ar % 2 == 0]
print(result)
print(result1)

[1 2 4 7]
[2 4 6]


## ndarray 연산

In [48]:
ar = np.array([1,2,3,4,5])
br = np.array([1,2,3,4,5])
cr = np.array([1,2,3,4])
print(ar + br)
# print(ar + cr)  # 에러
print(ar + 1)

[ 2  4  6  8 10]
[2 3 4 5 6]


In [57]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([1,2,3])
print(a+b)
c = np.array([1,2])
d = np.array([1,2,3,4]).reshape(2,2)
print(c+d)

[[2 4 6]
 [5 7 9]]
[[2 4]
 [4 6]]


In [61]:
# 논리 연산
ar = np.array([1,2,3,4,5])
br = np.array([10,20,False,40,0])

print(ar > br)  # [False False  True False  True]
print(np.not_equal(ar, br))  # [ True  True  True  True  True]
print(np.logical_xor(ar, br))  # [False False  True False  True]

[False False  True False  True]
[ True  True  True  True  True]
[False False  True False  True]


In [63]:
# 연산 후 할당
ar = np.array([1,2,3,4,5])
br = np.array([10,20,False,40,0])

ar += br
print(ar)  # [11 22  3 44  5]

print(1 in ar)  # False
print([1,2] in ar)  # False
print([1,100] in ar)  # False

[11 22  3 44  5]
False
False
False


C:\Users\USER\AppData\Local\Temp\ipykernel_14128\2013362749.py:9: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  print([1,2] in ar)
C:\Users\USER\AppData\Local\Temp\ipykernel_14128\2013362749.py:10: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  print([1,100] in ar)


In [66]:
# 벡터화된 함수 적용

# 매개 변수에 100을 더해서 반환하는 함수 만들기

def add100(a):
    return a + 100

# 벡터화된 함수로 수정
vec_add100 = np.vectorize(add100)


ar = np.array([1,2,3,4,5])
print(add100(ar))
print(vec_add100(ar))


# lambda 함수 이용
print(np.vectorize(lambda i:i+100)(ar))

[101 102 103 104 105]
[101 102 103 104 105]
[101 102 103 104 105]


## Transpose

In [77]:
matrix = np.array(range(1,11)).reshape(5,2)
print(matrix)
print(matrix.T)  # 전치

m = np.random.normal(size=(3,4,5))
print(np.shape(m))
tm = m.transpose((2,1,0))
print(np.shape(tm))

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[ 1  3  5  7  9]
 [ 2  4  6  8 10]]
(3, 4, 5)
(5, 4, 3)


## Random

In [133]:

cards = np.array(range(1,49))
print(cards)

permute1 = np.random.permutation(cards)
print(permute)


permute = np.random.permutation(cards)
print(permute)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]
[30  5 27 31 33 38 35 41  8 11 12 32 34 28 48  3 47 19 16 29 23 17 42 21
 43  9 14 26  6 18 36 15 39  2 13 44 25  7 24 37 22 20 10 40 46  4  1 45]
[30  5 27 31 33 38 35 41  8 11 12 32 34 28 48  3 47 19 16 29 23 17 42 21
 43  9 14 26  6 18 36 15 39  2 13 44 25  7 24 37 22 20 10 40 46  4  1 45]


## 기본 통계 함수

In [148]:
matrix = np.random.uniform(size=(3,2))
print(matrix)
print(matrix.sum())
print(matrix.std())  # 모표준편차
print(matrix.std(ddof=1))  # 표본표준편차 - 자유도 1
print(np.percentile(matrix, 75)) # 75%에 해당하는 값
# 행 단위 열 단위 합계
print(matrix.sum(axis=0))  # 열 마다 계산
print(matrix.sum(axis=1))  # 행 마다 계산
print(matrix.sum(axis=1, keepdims=True))  # 행 마다 계산 - matrix와 동일한 차원으로 반환

print(matrix.argmax(axis=1))
print(matrix.prod(axis=0))

[[0.26473016 0.39782075]
 [0.55282148 0.16494046]
 [0.36980809 0.14644176]]
1.8965627126489863
0.14134584265896327
0.15483661286778033
0.3908175877560568
[1.18735974 0.70920298]
[0.66255092 0.71776194 0.51624986]
[[0.66255092]
 [0.71776194]
 [0.51624986]]
[1 0 0]
[0.05412087 0.00960903]


In [152]:
ar = np.array([10,4,467,23,2])
result = np.sort(ar)  # 데이터 정렬
print(result)
print(ar)

br = np.array([[10,40,60],[20,40,24],[4,3,2]])
result = np.sort(br, axis=0)
print(result)

[  2   4  10  23 467]
[ 10   4 467  23   2]
[[ 4  3  2]
 [10 40 24]
 [20 40 60]]


In [164]:
x = range(1,51)
matrix = np.array(x).reshape(10,5)

# 행과 열의 개수 가져오기
print(matrix.shape)
print(type(matrix.shape))
cnt = matrix.shape[0]
print(cnt)

# 데이터 분할(7 : 3) - split()
help(np.split)
train, validation, test = np.split(matrix, [int(cnt * 0.7), int(cnt*0.9)])
print(train)
print(validation)
print(test)

(10, 5)
<class 'tuple'>
10
Help on function split in module numpy:

split(ary, indices_or_sections, axis=0)
    Split an array into multiple sub-arrays as views into `ary`.
    
    Parameters
    ----------
    ary : ndarray
        Array to be divided into sub-arrays.
    indices_or_sections : int or 1-D array
        If `indices_or_sections` is an integer, N, the array will be divided
        into N equal arrays along `axis`.  If such a split is not possible,
        an error is raised.
    
        If `indices_or_sections` is a 1-D array of sorted integers, the entries
        indicate where along `axis` the array is split.  For example,
        ``[2, 3]`` would, for ``axis=0``, result in
    
          - ary[:2]
          - ary[2:3]
          - ary[3:]
    
        If an index exceeds the dimension of the array along `axis`,
        an empty sub-array is returned correspondingly.
    axis : int, optional
        The axis along which to split, default is 0.
    
    Returns
    ---