# numpy

## 속도비교

In [2]:
import numpy as np
import datetime

In [102]:
# list의 작업 시간
li = list(range(1, 1000000))
print(type(li))

# 현재 시간 저장
start = datetime.datetime.now()

# 모든 요소에 10을 곱해서 list 수정
for i in range(len(li)):
    li[i] = li[i] * 10

# 현재 시간 저장
end = datetime.datetime.now()

time = end-start
print(time)

<class 'list'>
0:00:00.108080


In [103]:
# ndarray의 작업 시간
ar = np.arange(1, 1000000)

# 현재 시간 저장
start = datetime.datetime.now()

# 모든 요소에 10 곱함
ar = ar * 10

# 현재 시간 저장
end = datetime.datetime.now()

time = end-start
print(ar)
print(time)

[     10      20      30 ... 9999970 9999980 9999990]
0:00:00.001995


In [29]:
# 배열 정보 확인
ar = np.array([1,2,3])
print(type(ar))  # ar의 자료형 <class 'numpy.ndarray'>
print(ar.dtype)  # ar에 저장된 요소의 자료형 int32
print(ar.ndim)  # ar의 차원 1
print(ar.shape)  # ar의 모양 (3,)

<class 'numpy.ndarray'>
int32
1
(3,)


In [40]:
ar = np.array([[1,2,3],[4,5,6]])  
print(ar.ndim)  # 2
print(ar.shape)  # (2, 3)

2
(2, 3)


In [56]:
# 생성 함수
# arange([start,] stop[, step,], dtype=None)  # 개수를 지정하지 않고 시작위치, 종료위치, 간격 설정해서 데이터 생성
ar = np.arange(1, 100, 2)
print(ar)  # [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95 97 99]
# linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)  # 확률, 통계 실습할 때 많이 사용
ar = np.linspace(1, 100, num=10)
print(ar)  # [  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]
print(np.arange(10))

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]
[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]
[0 1 2 3 4 5 6 7 8 9]


In [66]:
print(np.zeros(4))
print(np.zeros((1,2)))
print(np.ones(2))
print(np.ones((2,3)))

[0. 0. 0. 0.]
[[0. 0.]]
[1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [69]:
print(np.zeros_like([[1,2,3],[1,2,3]]))
print(np.ones_like((4,5)))

[[0 0 0]
 [0 0 0]]
[1 1]


In [77]:
print(np.empty((4,3)))
print(np.empty_like((4,3)))

[[9.16112842e-312 3.16202013e-322 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 4.08073272e-033]
 [2.03794954e+160 1.48643040e-076 1.05140399e-046]
 [1.79247159e+160 4.11848079e-033 2.21472074e+160]]
[4 5]


In [83]:
print(np.eye(3,2))
print(np.identity(3))

print(np.eye(3, k=1))
print(np.eye(3, k=-1))

[[1. 0.]
 [0. 1.]
 [0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [89]:
square = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(square)
print(np.diag(square))  # [1 5 9]
print(np.diag(square, k=-1))  # [4 8]
print(np.diag(square, k=1))  # [2 6]

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 5 9]
[4 8]
[2 6]


In [3]:
ar = np.array([1,2,'3'])  # 문자열 배열
print(ar)
ar = np.array([1,2,'3'], dtype=np.int32)  # 자료형 정수로 지정
print(ar)
br = ar.astype(np.int32)  # 기존 배열 자료형 변경
print(br)

['1' '2' '3']
[1 2 3]
[1 2 3]


In [100]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)  # 3X3 행렬
ar = matrix.reshape(-1)  # 1차원
print(ar)
ar[0] = 101
print(ar)
print(matrix)  # 같이 바뀜

fl = matrix.flatten()
print(fl)
fl[0] = 201
print(fl)  # 복사본
print(matrix)  # 바뀌지 않음

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
[101   2   3   4   5   6   7   8   9]
[[101   2   3]
 [  4   5   6]
 [  7   8   9]]
[101   2   3   4   5   6   7   8   9]
[201   2   3   4   5   6   7   8   9]
[[101   2   3]
 [  4   5   6]
 [  7   8   9]]


In [136]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)
print(matrix[0])  # [1 2 3]
print(matrix[0][1])  # 2
print(matrix[:,0])  # [1 4 7]
print(matrix[0:2, 1])  # [2 5]
print()

# 인덱싱
ar = matrix[0]
br = matrix[0,]
print(ar)  # [1 2 3]
print(br)  # [1 2 3]
print()

ar[0] = 100
print(ar)  # [100   2   3]
print(br)  # [100   2   3]
print(matrix)
print()

br[0] = 20
print(ar)  # [20   2   3]
print(br)  # [20   2   3]
print(matrix)
print()

# list 이용하는 인덱싱 - 팬시 인덱싱
cr = matrix[[0]]
# 범위를 이용하는 형태 - 슬라이싱
dr = matrix[0][0:-1]
print(cr)
print(dr)
print()

cr[0, 0] = 30
print(cr)
print(dr)
print(matrix)
print()

dr[0] = 40
print(cr)
print(dr)
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
2
[1 4 7]
[2 5]

[1 2 3]
[1 2 3]

[100   2   3]
[100   2   3]
[[100   2   3]
 [  4   5   6]
 [  7   8   9]]

[20  2  3]
[20  2  3]
[[20  2  3]
 [ 4  5  6]
 [ 7  8  9]]

[[20  2  3]]
[20  2]

[[30  2  3]]
[20  2]
[[20  2  3]
 [ 4  5  6]
 [ 7  8  9]]

[[30  2  3]]
[40  2]
[[40  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [134]:
ar = np.array([4,6,10,364,23,5])
br = np.array([5,1,467,34,5,3])

# print(br[(ar >= 10) and (ar <= 30)])  # 에러
print(br[(ar >= 10) & (ar <= 30)])  # [467   5]


[467   5]
